### ISSUE TITLE
Game Crash on startup (with Solution for german language)

### ISSUE THREAD

**Issue by PhilHieg** [LBLuffy/HoloHud#10]
After installing the HoloUi/HoloHud mod, my game crashed when trying to start.
The Problem is in the `\mods\Holo\Loc\GR.txt` file.

1.  Line 29: change `"Holo/Enable" : Aktiviere $option"` to `"Holo/Enable" : "Aktiviere $option"`
2.  Line 79: either change `"Holo/Black":"Schwarz":"Hellblau"` to `"Holo/Black":"Schwarz"` or `"Holo/Black":"Schwarz", "Holo/Light Blue:"Hellblau"`

After those changes the Hud works fine

**Comment by Luffyyy** [comment]
Thanks, don't worry I know how to deal with json files :)
