### ISSUE TITLE
Chinese character support

### ISSUE THREAD

**Issue by Yarukon** [LBLuffy/HoloHud#101]
this ui doesn't support with chinese character, displayed as underline

**Comment by Luffyyy** [comment]
I'm not super sure how to test this, in Japanese the IME doesn't seem to want to write the characters at all but forcibly putting them in chat seems to work just fine so I don't think this is the mod's fault. Sorry for late response.

**Comment by Yarukon** [comment]
not the chatbox, its the teammates name become underline when displaying CJK characters
