### ISSUE TITLE
Request: Lite Option/Variant

### ISSUE THREAD

**Issue by SnazzyJovialWyrm** [LBLuffy/HoloHud#106]
Could you possibly create a "lite" variant that applies the HoloUI aesthetic to the base game's UI rather than completely changing it, along with the option to have the base game's health/armor gauge overlaying the player avatar icon? Additionally, would it be possible to implement an option that crops player's avatars into circles, or is that asking for too much?

**Comment by Luffyyy** [comment]
Unfortunately no I'll most likely not add any features anymore.

I am not into making versions of the mod as you can just simply add options to do these things. You can already turn off a lot of things.
 
Closest combo of avatar + circular health is this mod https://modworkshop.net/mod/22152 You could try using this with the mod.

**Comment by SnazzyJovialWyrm** [comment]
Fair enough. The reason I asked is because I really like the color customization and avatar feature of HoloUI, but the compactness of the UI itself and lack of a health/armor and interaction gauge really puts me off from using the hud.
