### ISSUE TITLE
Some spots did not use custom fonts

### ISSUE THREAD

**Issue by Hinaomi** [LBLuffy/HoloHud#109]
Font used : [DINPro Bold Font](https://modworkshop.net/mod/31445)

The custom font did not affect on some spots, mainly Point of No Return and Hostage counts.

![20210331000620_1](https://user-images.githubusercontent.com/77623869/113028784-e4488c80-91b5-11eb-8220-cdb0a654643d.jpg)

**Comment by Luffyyy** [comment]
Not exactly an issue, this has to do with the font choice of the HUD. Replace the noshadow font too.
