### ISSUE TITLE
Profile List White Rectangle

### ISSUE THREAD

**Issue by thomasR-347711** [LBLuffy/HoloHud#114]
When you enter to the profile list it appears a white rectangle I hope you can fix it ;) 

https://user-images.githubusercontent.com/82061497/113779760-94614c80-9704-11eb-852d-5daddd541ae6.mp4

**Comment by TheSuitManX** [comment]
Sorry, It´s a rectangle not a triangle.

**Comment by thomasR-347711** [comment]
Sorry, was a bug of WolfHUD
