### ISSUE TITLE
Segfault when starting several heists

### ISSUE THREAD

**Issue by fuzxi** [LBLuffy/HoloHud#115]
My only installed mods are BeardLib, HoloUI and SuperBLT (compiled from latest git commit). I had the same issue with an older version of SuperBLT, but I don't know when that was compiled. I can confirm identical crash logs on First World Bank and No Mercy, but no issues on Diamond Store. I didn't test other heists.

Running on Manjaro Linux with native Linux version of Payday 2.

[crash.txt](https://github.com/Luffyyy/HoloUI/files/6288921/crash.txt)

**Comment by Luffyyy** [comment]
Could you send me your BLT log? This issue looks very similar to this https://github.com/simon-wh/PAYDAY-2-BeardLib/issues/333

**Comment by ZNixian** [comment]
Were these crashes repeatable?

Also, did they occur without HoloUI installed?

**Comment by fuzxi** [comment]
Yes, this crash happens 100% of the time, after the heist loading screen but immediately before the crew loadout screen. If I remove HoloUI from my mods folder, it does not crash, with or without BeardLib.

[2021_04_10_log.txt](https://github.com/Luffyyy/HoloUI/files/6289380/2021_04_10_log.txt)

**Comment by Luffyyy** [comment]
Alright I think I know what the problem is, thanks for reporting.

**Comment by Luffyyy** [comment]
Try downloading the latest commit, I changed the problematic code.

**Comment by fuzxi** [comment]
Yep, that fixed it. Thanks a lot!
