### ISSUE TITLE
attempt to index field '_timer_text' (a nil value)

### ISSUE THREAD

**Issue by MilanesaTM** [LBLuffy/HoloHud#116]
Application has crashed: C++ exception
mods/Holo/Hooks/HUD/HeistTimer.lua:27: attempt to index field '_timer_text' (a nil value)

SCRIPT STACK

func() @mods/Holo/Hooks/HUD/HeistTimer.lua:4
init() @mods/base/req/core/Hooks.lua:268
new() core/lib/utils/coreclass.lua:35
_create_heist_timer() lib/managers/hudmanagerpd2.lua:1325
original() lib/managers/hudmanagerpd2.lua:656
original() @mods/base/req/core/Hooks.lua:188
_setup_player_info_hud_pd2() @mods/base/req/core/Hooks.lua:265
setup() 4
setup() lib/managers/hudmanager.lua:330
load_hud() lib/managers/hudmanager.lua:317
init_finalize() lib/managers/hudmanager.lua:219
init_finalize() lib/setups/gamesetup.lua:704
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:442

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

Current thread: Main

**Comment by Luffyyy** [comment]
Not enough info
