### ISSUE TITLE
Can't find the options

### ISSUE THREAD

**Issue by Dushess** [LBLuffy/HoloHud#119]
what happened? the mod itself or my build here?

**Comment by Luffyyy** [comment]
???

**Comment by Dushess** [comment]
Just no options panel in mods section, where you can configure it.

**Comment by Luffyyy** [comment]
F2 or in mods options

**Comment by Dushess** [comment]
no reaction and no line in mods options, that's the problem. But I'll check again on clean installation.

**Comment by Dushess** [comment]
Gonna close for now....
