### ISSUE TITLE
Hud not showing

### ISSUE THREAD

**Issue by dawids04** [LBLuffy/HoloHud#12]
So I installed the hud and everything what it need but I have the base hud and no option to customizise it or something like that
btw. sorry for my english

**Comment by Luffyyy** [comment]
What do you mean? do you have the default hud?
Options can be accessed from mod options > HoloUI or by pressing F1
if it doesn't work that means you installed the hud incorrectly.

**Comment by dawids04** [comment]
problem solved I'm just stupid as fuck
