### ISSUE TITLE
Is it possible to disable only the contours of the bags and corpses?-(Maybe request)

### ISSUE THREAD

**Issue by AJAL8000** [LBLuffy/HoloHud#120]
I use other mods like this:
https://pd2mods.z77.fr/bag_contour.html

And I would like to keep outline colors that other mods give me. What part of the code or what should I do to just disable that specific mod function?

Since it always appears with the colors that HoloUI gives, and I would not want to disable all the other contours that it gives.

**Comment by AJAL8000** [comment]
@Luffyyy Thanks for the consideration and the code fix. Although I was hoping for a faster update 😅

**Comment by Luffyyy** [comment]
> @Luffyyy Thanks for the consideration and the code fix. Although I was hoping for a faster update 😅

Yeah, apologizes for the delay 😅
