### ISSUE TITLE
Broken frame on AI name panels

### ISSUE THREAD

**Issue by TheTastyGravy** [LBLuffy/HoloHud#121]
The left and right sides of the frame teammate name panel will sometimes be missing depending on the characters brought and the UI settings (specifically 'show teammates full ammo' and 'compact teammate panel'). Different variations of characters and settings will cause different sections to become missing. While the examples below both use 'full' frame style, 'left line' and 'right line' will still have the lines missing.

'Show teammates full ammo' off and 'compact teammate panel' off
![Untitled](https://user-images.githubusercontent.com/43807068/132345094-9b482da5-e9a9-401b-b46b-a7babfbd7760.png)
'Show teammates full ammo' off and 'compact teammate panel' on
![Untitled1](https://user-images.githubusercontent.com/43807068/132345480-96b37976-2227-4711-aa4a-ea2ecee09abe.png)

**Comment by Luffyyy** [comment]
This is happening due to using lower resolution. I added an option that should allow you to change the HUD frame size (so 2 works for 720p)
