### ISSUE TITLE
PocoHUD Tracker not working after installing HoloUI

### ISSUE THREAD

**Issue by Qy0h** [LBLuffy/HoloHud#122]
Found out that the Tracker would be broken with HoloUI and I have to manually click "Apply and Reload" every time when I start a new game in order to make the tracker work again.

Before clicking "Apply and Reload"
![image](https://user-images.githubusercontent.com/91158070/134239903-c5804fcc-190b-439c-b451-fec3c0001d11.png)

After Clicking "Apply and Reload"
![image](https://user-images.githubusercontent.com/91158070/134239935-c2d8dd0b-0acd-4bf9-989f-471bdc6c4fbc.png)

This problem still happens even when I only have HoloUI,PocoHud and Additional PocoHud Trackers installed

**Comment by Arlwe** [comment]
Any news, Do the bug has been fixed?

**Comment by Luffyyy** [comment]
Doesn't seem to happen in my case, maybe it was fixed in poco's side
