### ISSUE TITLE
CTD upon entering pre-planning

### ISSUE THREAD

**Issue by Kululu4200XD** [LBLuffy/HoloHud#123]
I was trying to follow my friend's setup which uses VanillaHud+, Void UI, PocoHUD and HOLO UI (holo UI is simply beautiful)
I've had multiple crashes, posted below are 2 different crash dumps, hopefully this helps in some way 

Application has crashed: C++ exception
mods/Holo/Hooks/HUD/BlackScreen.lua:12: attempt to index field '_skip_circle' (a nil value)

SCRIPT STACK

func() @mods/Holo/Hooks/HUD/BlackScreen.lua:3
init() @mods/base/req/core/Hooks.lua:268
new() core/lib/utils/coreclass.lua:35
setup_blackscreen_hud() lib/managers/hudmanagerpd2.lua:1901
setup() 7
setup() lib/managers/hudmanager.lua:330
load_hud() lib/managers/hudmanager.lua:317
func() @mods/Holo/Hooks/Menu/MenuHooks.lua:366
at_enter() @mods/base/req/core/Hooks.lua:182
trans_func() lib/states/gamestate.lua:22
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:945
end_update() lib/setups/gamesetup.lua:825
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:600

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

---------------------------------------------------------------------------------

Application has crashed: C++ exception
mods/Holo/Hooks/HUD/PlayerDowned.lua:18: attempt to index local 'timer_msg' (a nil value)

SCRIPT STACK

func() @mods/Holo/Hooks/HUD/PlayerDowned.lua:12
init() @mods/base/req/core/Hooks.lua:268
new() core/lib/utils/coreclass.lua:35
_create_downed_hud_original() lib/managers/hudmanagerpd2.lua:1467
_create_downed_hud() @mods/VanillaHUD Plus-prev/lua/AdvAssault.lua:259
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:665
_setup_player_info_hud_pd2_original() @mods/VanillaHUD Plus-prev/lua/HUDList.lua:113
_setup_player_info_hud_pd2() @mods/VanillaHUD Plus-prev/lua/DrivingHUD.lua:570
_setup_player_info_hud_pd2_original() @mods/Extra Heist Info/lua/hudmanagerpd2.lua:23
setup_player_info_hud_pd2() @mods/VanillaHUD Plus-prev/lua/EnemyHealthbar.lua:6
original() @mods/Void UI/lua/managers/HudManager.lua:222
original() @mods/base/req/core/Hooks.lua:188
_setup_player_info_hud_pd2() @mods/base/req/core/Hooks.lua:265
setup() 4
setup() lib/managers/hudmanager.lua:330
load_hud() lib/managers/hudmanager.lua:317
original() lib/managers/hudmanager.lua:219
init_finalize() @mods/base/req/core/Hooks.lua:265
init_finalize() lib/setups/gamesetup.lua:714
init_finalize() @mods/Extra Heist Info/lua/GameSetup.lua:31
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap

**Comment by Luffyyy** [comment]
Moving to #129, support is going to be added next version
