### ISSUE TITLE
persistent reticle

### ISSUE THREAD

**Issue by CombatPipe** [LBLuffy/HoloHud#128]
I may be about to look a fool for this, but when I installed HoloUI for the first time I also had a little black and white dot appear in the middle of my screen. I didn't think Holo would come with a reticle, but this was fine. 
What was less fine was that after I deleted my HoloUI files, the reticle remained. I've even noticed it being misaligned with the center of my screen on occasion. It's been this way for some time, even with other HUDs and crosshair mods. 
What can I do to get rid of it?

**Comment by Luffyyy** [comment]
If you removed the mod and it still shows up, then it can't be HoloUI. The mod doesn't patch anything. Check other mods that may cause it.
