### ISSUE TITLE
add VOIDUI support

### ISSUE THREAD

**Issue by LMauc** [LBLuffy/HoloHud#129]
Despite the fact that I deactivated the HOLOUI HUD in any way, it conflicted with VOIDUI, in my opinion it is obviously because files collide, but I think it must be because of the loading screens, which is where the game crashes

Probably the idea would be to add an option that allows disabling holoui loading screens

SCRIPT STACK

_create_input_panel() @mods/base/req/core/Hooks.lua:272
orig_init() @mods/VoidUI-master/lua/hud/HudChat.lua:70
init() @mods/Holo/Hooks/HUD/Chat.lua:12
new() core/lib/utils/coreclass.lua:35
_create_hud_chat() lib/managers/hudmanagerpd2.lua:716
original() lib/managers/hudmanagerpd2.lua:680
setup_player_info_hud_pd2() @mods/base/req/core/Hooks.lua:264
_setup_player_info_hud_pd2() @mods/VoidUI-master/lua/managers/HudManager.lua:228
setup() 4
setup() lib/managers/hudmanager.lua:330
load_hud() lib/managers/hudmanager.lua:317
init_finalize() lib/managers/hudmanager.lua:219
init_fin_orig() lib/setups/gamesetup.lua:763
init_finalize() @mods/The Fixes/gamesetup.lua:6
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:444

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        

-------------------------------

**Comment by Luffyyy** [comment]
I did some basic support, will need likely more thorough testing though.
