### ISSUE TITLE
Crash on starting a heist

### ISSUE THREAD

**Issue by Fixxwiss** [LBLuffy/HoloHud#15]
So i get this crash on starting up a heist. The three mods that seem to be colliding is Holo, Wolfhud, and oddly enough, the music module. Any clue what could be causing this? 

PAYDAY 2 Crash log
Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
Script stack:
          check_music_switch()  @mods/Music                                         
                                Module/MusicManager.lua:65                          
                  sync_start()                                                      
lib/states/ingamewaitingforplayers.lua:87  _start()                                            
                                lib/states/ingamewaitingforplayers.lua:73           
            start_game_intro()                                                      
lib/states/ingamewaitingforplayers.lua:493  check_start_game_intro()                            
                                lib/network/base/basenetworksession.lua:1625        
         on_set_member_ready()                                                      
lib/network/base/hostnetworksession.lua:974  lib/network/base/handlers/connectionnetworkhandler.lua:608  
-------------------------------

**Comment by Luffyyy** [comment]
Dunno I think the crash is unlikely to be caused by the mod please first test without HoloUI and see if you crash.

**Comment by Fixxwiss** [comment]
Ok, did some bugtesting. Wasn't this mod, but one custom song was crashing my game for some reason. Well, it was worth checking with higher powers anyways.

**Comment by Fixxwiss** [comment]
It was 6:24 out of this one https://modworkshop.net/mydownloads.php?action=view_down&did=19495
Strange that it is that specific one, and not any else.
