### ISSUE TITLE
Mouse renders behind options ComboBox

### ISSUE THREAD

**Issue by bamq** [LBLuffy/HoloHud#17]
The mouse renders behind combo boxes (I think that's what they're called) in the options menu.
https://i.gyazo.com/f4f6cdd0467f38edb3b3b257e6acafe0.mp4
I feel like this has been around for a while.

**Comment by Luffyyy** [comment]
Currently I am waiting to get BeardLib dev branch to master there the menu should be a little better.

**Comment by bamq** [comment]
Ok. I suspected it had something to do with BeardLib.
