### ISSUE TITLE
Crash When Opening Inventory With Update 150

### ISSUE THREAD

**Issue by NerdVenom** [LBLuffy/HoloHud#22]
Application has crashed: C++ exception
mods/Holo/Hooks/Menu/MultiProfileItemGUI.lua:6: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlGetCurrentServiceSessionId

**Comment by Luffyyy** [comment]
fixed if you haven't noticed.
