### ISSUE TITLE
What does HOLO do that crashes MUI like this?

### ISSUE THREAD

**Issue by SaintHF** [LBLuffy/HoloHud#23]
Application has crashed: C++ exception
mods/MUI/lua/mui_manager.lua:127: attempt to call method 'set_max_stamina' (a nil value)

SCRIPT STACK

-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                       nvspcap  (???)     QueryShadowPlayInterfaceVersionRange                
                           ???  (???)     ???                                                 
                           ???  (???)     ???

**Comment by Luffyyy** [comment]
from what I recall HoloUI doesn't support MUI.

**Comment by SaintHF** [comment]
It would be pretty cool if it did though, don't you think?
