### ISSUE TITLE
UI not showing

### ISSUE THREAD

**Issue by spaceDragonDragonfromspace** [LBLuffy/HoloHud#26]
Ive reinstalled the mod, BeardLib AND BLT multiple times and F1 doesnt work, the mod doesnt even show up in the mods list and i still get the same HUD.

**Comment by Luffyyy** [comment]
can you post your latest log file from mods/logs?
you might have installed beardlib dev.

**Comment by spaceDragonDragonfromspace** [comment]
Ive downloaded the BeardLib provided in the link on the modworkshop (rip lastbullet) post. Ill send the log next chance i get.

**Comment by spaceDragonDragonfromspace** [comment]
I uh.. Cant find the log. Or rather im not fully aware of which log youre talking about. It doesnt crash, the game launches fine but it just doesnt show up, just the usual UI

**Comment by Luffyyy** [comment]
mods/logs and then current date text file

**Comment by spaceDragonDragonfromspace** [comment]
All the mods i have besides HoloUI are music or sound overrides (Hotline Miami Music Pack, some meme noises), no other BLT mods.

[2017_07_20_log.txt](https://github.com/Luffyyy/HoloUI/files/1161697/2017_07_20_log.txt)
_sorry if thats the wrong log, i dont mod payday much :l_
oh yeah its also somewhat empty hence why im assuming its the wrong one. Ill play a game n ill see what happens

**Comment by Luffyyy** [comment]
then give me the log of the day it happened.

**Comment by spaceDragonDragonfromspace** [comment]
its exactly the same only multiple times. The game acts weird when i play it, long load times, frames dip frequently, the screen tears but with black bars (that ones probably not the mod but maybe the rest). Maybe a reinstall? Like full game
[2017_07_19_log.txt](https://github.com/Luffyyy/HoloUI/files/1161739/2017_07_19_log.txt)

**Comment by Luffyyy** [comment]
Do you have BLT installed? like you have the bar that says if there are any updates?
if not you probably installed BLT through paydaymods which has it outdated get it here instead:
https://github.com/JamesWilko/Payday-2-BLT/releases

**Comment by spaceDragonDragonfromspace** [comment]
Okay, that was it. If im not mistaken, paydaymods advertises itself as the place to get BLT. Thank you, and i have a follow up question if you dont mind; can i have override mods installed that change the backgrounds? The grey, although clean, is a bit dull. 

_again thanks many fuckloads <3_

**Comment by Luffyyy** [comment]
You can disable the colored background in options  

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by spaceDragonDragonfromspace** [comment]
Thank you <3
