### ISSUE TITLE
Uncompatibility between PocoHUD and HoloUI

### ISSUE THREAD

**Issue by Esawo** [LBLuffy/HoloHud#28]
As the title says, for some odd reason, some PocoHUD features don't work anymore with HoloUI.
More specifically, the bottom info box doesn't work anymore, as it seems to be conflicting with the Holo HUD (when I disable it and restart the game, I can see the bottom info box). It's not too bothering, though that feature was great and worked correctly, unlike most kill counters. You might want to know that the buff icons work perfectly.
The version of HoloUI used was the latest, 2.01 (or at least what I've downloaded on modworkshop.com).
EDIT: Can I be notified if this issue will be fixed/if it is fixed? And it seems to work for other players aswell, I just can't see mine.

**Comment by Sydch** [comment]
It's still an issue for latest revision on GitHub.

**Comment by Luffyyy** [comment]
I tried fixing some of the issues but bare in mind that it isn't perfect.
