### ISSUE TITLE
HoloUI, Wolfhud compatibility issue 

### ISSUE THREAD

**Issue by Thirtytree** [LBLuffy/HoloHud#29]
Disabling customhud in wolfhud options didn't replace the HUD with Holo's. On mission startup it crashes this is the log: 

Application has crashed: C++ exception
mods/WolfHUD/Core.lua:611: attempt to concatenate local 'id' (a table value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlGetCurrentServiceSessionId   

I know this isn't your issue but I did see the feature that was supposed to communicate with Wolfhud

**Comment by Luffyyy** [comment]
I'll look into it when I can

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NerdVenom** [comment]
You might have to do something like this:
In WolfHUD/lua/customhud.lua, add this to the top of the file 
`if SystemFS:exists("mods/Holo/mod.txt") then
return
end`

That will completely disable the CustomHUD lua file while HoloUI is installed. Might have to do that to other parts as well, not sure.

**Comment by Luffyyy** [comment]
Pretty sure custom hud has an option
Also that's a really bad method of checking you could do 'if Holo'

**Comment by Luffyyy** [comment]
Sorry for the long wait, but this should be fixed in beta 3.0.
There are some issues yet to be fixed like kill counters and wolfhud's green interaction circle being visible with the new interaction that Holo has, feel free to report any other issues.
