### ISSUE TITLE
Mod options Resolution

### ISSUE THREAD

**Issue by segabl** [LBLuffy/HoloHud#3]
Some resolutions may make the mod menu hard to navigate due to the top part of the menu being "cut off". My resolution is 1680x1050 which leads to black bars on the top and bottom of the menu that overlap the tabs of the mod menu.
In general it seems the mod is made for 16:9 resolution. Ingame, the huds vertical distance from the border is higher than the horizontal one on 16:10 for instance.

**Comment by segabl** [comment]
Adding to the previous, the carry info panel overlaps with the inventory panel (keycards crowbar etc) when using the default team mate panel (probably also due to incorrect aspect ratio). The seperators in the card drop screen overlap with the cards when using the unmodified lobby option as well as the soundtrack list overlapping the tabs in the ingame lobby (already reported though)

**Comment by Luffyyy** [comment]
Fixed all hopefully.

**Comment by segabl** [comment]
unfortunately the seperators in the card drop screen still overlap with the cards, everything else works just fine now.

**Comment by Luffyyy** [comment]
hmm was sure i fixed that well i will see.

**Comment by segabl** [comment]
only happens when you use the default lobby
