### ISSUE TITLE
Crash with last update

### ISSUE THREAD

**Issue by NicoTine34** [LBLuffy/HoloHud#30]
Application has crashed: C++ exception
mods/Holo/Base.lua:64: attempt to call method 'contrast' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlSizeHeap                                         
                         ntdll  (???)     ZwQueryInformationProcess                           
                      aswhookx  (???)     ???                                                 
                         ntdll  (???)     NtQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name

**Comment by Luffyyy** [comment]
Update beardlib
