### ISSUE TITLE
BLT 2.0 - LuaJIT Update

### ISSUE THREAD

**Issue by Emanuel1224** [LBLuffy/HoloHud#31]
So BLT switched the runtime of the game to LuaJIT which means all mods will have to be updated.

Quoted from the Payday 2 community post on the update:

> "We have switched the runtime of the game to LuaJIT which will result in an overall better game performance. Sadly this means that Lua mods using the BLT will not work until they got updated."

Update?

**Comment by Luffyyy** [comment]
I'll work on that tomorrow.

**Comment by Emanuel1224** [comment]
The hud is broken again, theres another update.
![image](https://user-images.githubusercontent.com/31522594/29998901-e92e70a6-900c-11e7-9188-b751d5caa4a0.png)
