### ISSUE TITLE
problems with holo 

### ISSUE THREAD

**Issue by b33croft1992** [LBLuffy/HoloHud#33]
is there another blt update out just want to make sure beccause im having problems with this mod holo ui 

Application has crashed: C++ exception
mods/Holo/Hooks/Menu/MultiProfileItemGUI.lua:17: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

func() @mods/Holo/Hooks/Menu/MultiProfileItemGUI.lua:17
update() @mods/base/req/core/Hooks.lua:267
init_orig() lib/managers/menu/multiprofileitemgui.lua:46
original() @mods/WolfHUD-master/lua/ProfileMenu.lua:334
init() @mods/base/req/core/Hooks.lua:260
new() core/lib/utils/coreclass.lua:35
original() lib/managers/menu/missionbriefinggui.lua:2856
init() @mods/base/req/core/Hooks.lua:260
new() core/lib/utils/coreclass.lua:35
create_mission_briefing_gui() lib/managers/menu/menucomponentmanager.lua:2930
create() lib/managers/menu/menucomponentmanager.lua:2921
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/gamesetup.lua:650
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.327.
	CPU : Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 730 / nvldumd.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8145MB 848KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Luffyyy** [comment]
Fixed already
