### ISSUE TITLE
Presenter Stuck on screen?

### ISSUE THREAD

**Issue by Vengeance2** [LBLuffy/HoloHud#34]

**Comment by Vengeance2** [comment]
How can i fix this problem with HoloUI? Presenter stays in the middle of the screen 
![20170908024908_1](https://user-images.githubusercontent.com/31744243/30201474-87e189b8-9440-11e7-8d17-ac0ed6833f49.jpg)

**Comment by Luffyyy** [comment]
Fixed in 2.1

**Comment by Luffyyy** [comment]
Make sure you update BeardLib and HoloUI.
