### ISSUE TITLE
Crash when start a heist

### ISSUE THREAD

**Issue by NicoTine34** [LBLuffy/HoloHud#35]
With last update my game crash when i start loading a heist. I unistall the mod , no more crash.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???

**Comment by UaltarH** [comment]
same here
