### ISSUE TITLE
Crash upon joining players heist :(

### ISSUE THREAD

**Issue by hardyboyz373** [LBLuffy/HoloHud#4]
this is the crash log:

Tue Nov 01 22:25:43 2016

Application has crashed: C++ exception
...ds/LoadingScreenInfo/levelloadingscreenguiscript.lua:762: attempt to compare number with nil

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     Sleep                                               
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     GetProcAddressForCaller                             
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: LoadingEnvironment

-------------------------------

**Comment by Luffyyy** [comment]
Disable HoloUI's loading screen for loading screen info to not crash the game

**Comment by hardyboyz373** [comment]
Alright thanks! :D
