### ISSUE TITLE
CompactHUD no longer working

### ISSUE THREAD

**Issue by Brendansports** [LBLuffy/HoloHud#40]
Like the title says, Even though you discontinued work on it, it has worked fine until recently with the new Crimefest update that screwed it up. Since youve stopped working on it maybe you can add an option to holoui to change the Teammate Hud ONLY since thats really the only noticeable thing in CompactHUD.

**Comment by Luffyyy** [comment]
you should be able to disable most parts of the mod, if there's anything more that needs to be disabled you can suggest adding another option.

**Comment by Brendansports** [comment]
No nothing needs to be added disabling wise. but you noted you MIGHT add an option for a more compact lightweight hud option in the HoloUI since compacthud is now forever bugged now seems like a good time.

**Comment by Luffyyy** [comment]
well I did but I don't really have time to work on it, since it's more standalone hud(instead of HoloUI which builds upon the default hud) it will take time to make it properly work, if you wish for a minimalistic hud you can set the spacing/scaling.
