### ISSUE TITLE
Crashes when going into crime.net.

### ISSUE THREAD

**Issue by Esawo** [LBLuffy/HoloHud#42]
Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value

SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:294
_update() @mods/base/lua/MenuSetup.lua:6
update() @mods\PocoHud3\poco\common.lua:309
orig__update() core/lib/setups/coresetup.lua:537

**Comment by Luffyyy** [comment]
https://github.com/Luffyyy/HoloUI/issues/38#issuecomment-341821649
