### ISSUE TITLE
Newest Beardlib (github ver) menu uncompatibility

### ISSUE THREAD

**Issue by Esawo** [LBLuffy/HoloHud#43]
Gets a fancy black screen (option part only, not the entire screen) with the new Beardlib when opening the Holo UI menu. Crashes on option click.
I don't have the latest BLT, though that shouldn't be an issue.
-------------------------------
Application has crashed: C++ exception
mods/Holo/Classes/OptionsMenu.lua:447: attempt to index field '_resize' (a nil value)

       return false
end
unction MenuUI:MouseMoved(o, x, y)

SCRIPT STACK

mouse_press() 317
lib/managers/mousepointermanager.lua:308

-------------------------------

**Comment by Luffyyy** [comment]
Did you install the latest version? It's in github

**Comment by Esawo** [comment]
Of Beardlib? Holo UI? Yes. Well it's not big of an issue for now, a downgrade to a previous Beardlib is easily done.

**Comment by Luffyyy** [comment]
That makes no sense, a downgrade would result in a broken menu for HoloUI 3.0, anyway closed.
