### ISSUE TITLE
Won't Work/Crashes

### ISSUE THREAD

**Issue by breezyzero** [LBLuffy/HoloHud#45]
I did all the directions on how to download the hud. I dragged it into the mods folder and have the latest  BeardLib. When I load up my game, I see the hud but when I click "crime.net" the game crashes.

Also when i go into mod settings it dosent show up to edit it

**Comment by Luffyyy** [comment]
1. You don't report crashes without a crashlog
2. https://github.com/Luffyyy/HoloUI/issues/38#issuecomment-341821649

**Comment by breezyzero** [comment]
----------------------------------------------------------------------

Sun Nov 19 19:17:43 2017


Application has crashed: C++ exception
mods/Holo/Classes/OptionsMenu.lua:447: attempt to index field '_resize' (a nil value)

	return false
end
function MenuUI:MouseMoved(o, x, y)


SCRIPT STACK

mouse_press() 317
lib/managers/mousepointermanager.lua:308


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Sun Nov 19 19:21:51 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Sun Nov 19 19:27:38 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Sun Nov 19 19:27:58 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Sun Nov 19 19:29:41 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Sun Nov 19 19:52:03 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Sun Nov 19 20:02:24 2017


Application has crashed: C++ exception
[string "lib/units/weapons/newraycastweaponbase.lua"]:203: attempt to index a nil value



SCRIPT STACK

clbk_part_unit_loaded() lib/managers/weaponfactorymanager.lua:848
assemble_from_blueprint() @mods/RestorationMod/lua/sc/managers/weaponfactorymanager.lua:95
assemble_from_blueprint() lib/units/weapons/newraycastweaponbase.lua:132
add_unit_by_factory_name() @mods/RestorationMod/lua/sc/units/player/playerinventory.lua:19
_internal_load() lib/managers/playermanager.lua:629
spawned_player() lib/managers/playermanager.lua:903
set_unit() lib/network/base/networkpeer.lua:2249
lib/network/handlers/unitnetworkhandler.lua:48


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Sun Nov 19 20:46:03 2017


Application has crashed: C++ exception
mods/CompactHUD/hud/hudteammate.lua:409: attempt to index local 'grenades' (a nil value)



SCRIPT STACK

init() @mods/CompactHUD/hud/hudteammate.lua:180
new() core/lib/utils/coreclass.lua:35
_create_teammates_panel() @mods/CompactHUD/hud/hudmanager.lua:27
_setup_player_info_hud_pd2() lib/managers/hudmanagerpd2.lua:642
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
init_finalize() lib/managers/hudmanager.lua:169
init_finalize() lib/setups/gamesetup.lua:621
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Wed Nov 22 17:29:22 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.454.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Wed Nov 22 17:30:24 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.454.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Wed Nov 22 17:33:14 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.454.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Wed Nov 22 18:17:26 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.454.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))



----------------------------------------------------------------------

Wed Nov 22 18:22:21 2017


Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value



SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.454.
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     32708MB 504KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Logitech G35 Headset))

**Comment by Luffyyy** [comment]
There are two crashlogs one that keeps old ones and one that is the latest, either way, you ignored the 2nd point and I forgot to close this.
