### ISSUE TITLE
Wont Work/Crashes (with crash log)

### ISSUE THREAD

**Issue by breezyzero** [LBLuffy/HoloHud#46]
crashes when going to crime.net
____________________________________
Application has crashed: C++ exception
mods/Holo/Hooks/CrimeNetManager.lua:31: attempt to index a nil value

SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:267
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:2179
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:766
update() lib/setups/menusetup.lua:296
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------

Sun Nov 19 19:17:43 2017

Application has crashed: C++ exception
mods/Holo/Classes/OptionsMenu.lua:447: attempt to index field '_resize' (a nil value)

	return false
end
function MenuUI:MouseMoved(o, x, y)

SCRIPT STACK

mouse_press() 317
lib/managers/mousepointermanager.lua:308

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by Luffyyy** [comment]
Thanks for ignoring the 2nd point from before.

Just update your mod from GitHub how hard is it.
