### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by tomasseisde** [LBLuffy/HoloHud#58]
Hello. I cant change backgrounds all is grey, can you help ,me please? my game looks shit beeing all grey Lol

**Comment by Luffyyy** [comment]
Options menu.

IMO the game looks like shit with its default backgrounds btw.

**Comment by tomasseisde** [comment]
man, could you take the time to answer me properly and tell me step by step what i have to do? there´s any walkthorught in internet?

**Comment by Luffyyy** [comment]
You just go to options menu and disable 'Colored menu backgrounds' under menu section, just search for options before you report anything.

Press F2 / or go to mod options > HoloUI Options

**Comment by tomasseisde** [comment]
where should i put my images? Im a noob ):
