### ISSUE TITLE
Lobby names being cut off

### ISSUE THREAD

**Issue by Kriosasacil** [LBLuffy/HoloHud#59]
Not sure why it is doing this.
![image](https://user-images.githubusercontent.com/27170622/34229993-64d570c8-e5a4-11e7-8a28-8d3989d85e24.png)

**Comment by Luffyyy** [comment]
You're not running any other mods?

**Comment by Kriosasacil** [comment]
Thought this was the only hud related mod I had installed but I  do have TranslucentMissionBriefingUI installed so I'll try uninstalling that.

**Comment by Kriosasacil** [comment]
Still doing it without that mod. Just started using the UI so I haven't tweaked to much

**Comment by Kriosasacil** [comment]
It appears it is the font size option under menu settings. I had it set to 8 instead of 12 and it was making it cut off the screen.

**Comment by Luffyyy** [comment]
Alright I'll try fixing it
