### ISSUE TITLE
[Suggestion] Old circle health and armour

### ISSUE THREAD

**Issue by shadz43** [LBLuffy/HoloHud#62]
Could you bring back the old armour and health circle? even if its not colour changeable, Myself and a lot of people have issues seeing the small numbers and are used to a circle

**Comment by Luffyyy** [comment]
It depends, I'll most likely redo the teammate panel, but well, it's hard to maintain two modifications.

**Comment by EvilTater** [comment]
I agree. It's much easier to see health and armor as the circle. I have the bottom HUD disabled because the numbers were too annoying.

**Comment by Luffyyy** [comment]
Welp the mod is discontinued 🤷‍♀️ 
I am way too busy to work on it
