### ISSUE TITLE
BUG: locked out of interaction after using F2 menu

### ISSUE THREAD

**Issue by AnElbow** [LBLuffy/HoloHud#65]
Hi,

At any point after the lobby screen (when in the menu where you can buy assets after loading into a mission or actually playing ingame) if I use the F2 menu, I am unable to interact with anything that is not a menu. So the escape menu works but WASD and the mouse and all other bound keys to nothing.

Rebinding the button from F2 doesn't solve this.

Thank you

**Comment by floydfire** [comment]
Can confirm this, would be awesome to have an update just fixing things...
