### ISSUE TITLE
File/Folder case sensitivity issues

### ISSUE THREAD

**Issue by RomanHargrave** [LBLuffy/HoloHud#66]
WRT blt4linux/blt4l#107

CC @TheFinestSurgeon

Aforementioned issue appears to be caused by a discrepancy between folder and file names on disk and the way that they are referenced in code (specifically, `mods/Holo/Hooks/HUD` is expected, while `mods/Holo/Hooks/Hud` is the truth).

**Comment by Luffyyy** [comment]
I could've sworn I've changed that, github can be annoying at times.

**Comment by Luffyyy** [comment]
I use gitkraken and it just doesn't see that I've renamed the folder and I can't see any option on GitHub to rename a folder, any suggestions?

**Comment by RomanHargrave** [comment]
i'll have to get back with the issue later (work soon). It could be that the user downloaded a published copy from paydaymods which is still borked

**Comment by RomanHargrave** [comment]
Renaming a folder in git is essentially making a new folder and moving the old contents to the new folder.

**Comment by RomanHargrave** [comment]
ultimately, it is expressed as a complete removal of folder A and its files, and the addition of an identical (with the changes) folder in the same commit.

**Comment by Luffyyy** [comment]
Alright thanks.
