### ISSUE TITLE
Crashes on Resizing

### ISSUE THREAD

**Issue by thedpdman** [LBLuffy/HoloHud#68]
i get a crash error when i opened the menu for heists, so i deleted the lua. but crashes when i click f1 

here is the crash log for the menu Resizing?
Mon Jul 30 02:34:55 2018

Application has crashed: C++ exception
mods/Holo/Classes/OptionsMenu.lua:423: attempt to index field '_resize' (a nil value)

		end
		return true
	end

SCRIPT STACK

mouse_press() 386
lib/managers/mousepointermanager.lua:339

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???

**Comment by Luffyyy** [comment]
If you delete/modify code don't report me the crash of that edit, thanks.
