### ISSUE TITLE
Application has crashed: C++ exception

### ISSUE THREAD

**Issue by katabame** [LBLuffy/HoloHud#7]
Following is Clash log. (part of minidump)
```
mods/Holo/Hooks/Hud/HudPresenter.lua:8: attempt to index field '_bg_box' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     NtQueryVirtualMemory                                


-------------------------------

Current thread: Main

-------------------------------
```
If you need full- mini dump file, please tell me!
Thanks,

**Comment by Luffyyy** [comment]
What mods do you have installed?

**Comment by katabame** [comment]
I Usually using those mods
- [Chat_Time](https://www.dropbox.com/s/0utz23ogo4x8u7u/chattime_BLT1.zip?dl=0)
- [Lobby_Name](https://www.dropbox.com/s/nxm4169usqf5ibs/lobby_name_BLT2.zip?dl=0)
- [Default_Values](https://www.dropbox.com/s/jwdm62g09n2oqzo/default_values_BLT2.zip?dl=0)
- [JP_MOD](https://www.dropbox.com/s/3th9qjy7rxac9ax/_JP_MOD_BLT8.zip?dl=0)
- [InspirePriority](http://download.paydaymods.com/download/latest/InspirePriority)
- [Newbies Go Back To Overkill](http://download.paydaymods.com/download/latest/NGBTO)
- [Lobby Player Info](http://download.paydaymods.com/download/latest/LPI)
- [More Weapon Stats](http://download.paydaymods.com/download/latest/MWS)
- [Always Show Mod Icons](http://modworkshop.net/mydownloads.php?action=view_down&did=13975)
- [Drag and Drop Inventory](http://download.paydaymods.com/download/latest/DDI)
- [CustomFOV](http://modworkshop.net/mydownloads.php?action=view_down&did=14930)
- [Bag Contour](http://download.paydaymods.com/download/latest/BC)
- [Anti-Bobble](http://modworkshop.net/mydownloads.php?action=view_down&did=15363)
- [Bain Cant Cook For Shit](http://download.paydaymods.com/download/latest/BCCFS)
- [Customizable Crosshair](https://www.dropbox.com/s/u7ltbmogor9c1hl/CusCrosshair.zip?dl=0)
- [Buildb](http://download.paydaymods.com/download/latest/BDB)
- [Side Jobs In Lobby](http://download.paydaymods.com/download/latest/SDJBL)
- [JackHUD](https://github.com/BangL/JackHud)

`assets/mod_overwrite` is needed too?

**Comment by Luffyyy** [comment]
JackHUD from what i know is not compatible with HoloUI currently.

**Comment by katabame** [comment]
Okey, thanks to solve this issue.

I like this mod's UI. hope this mod goin' more greater than JackHUD
cheer *
