### ISSUE TITLE
ISSUE - The game crashes when i use the hacker perk deck and activate the pocket ECM.

### ISSUE THREAD

**Issue by ColorfulGoat** [LBLuffy/HoloHud#76]
The game seems to completely freeze when ever i use the pocker ECM in the hacker perk deck, tested it 4 times so far. Here is the crash log:

Fri Aug 24 03:26:56 2018

Application has crashed: C++ exception
mods/Holo/Hooks/HUD/Teammate.lua:386: attempt to perform arithmetic on local 'time_total' (a nil value)

SCRIPT STACK

activate_ability_radial() @mods/base/req/core/Hooks.lua:267
activate_teammate_ability_radial() lib/managers/hudmanagerpd2.lua:351
attempt_func() lib/managers/playermanager.lua:5327
attempt_ability() lib/managers/playermanager.lua:5272
_check_action_throw_projectile() lib/units/beings/player/states/playerstandard.lua:2239
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:979
update() lib/units/beings/player/states/playerstandard.lua:436
lib/units/beings/player/playermovement.lua:271

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.679.
	CPU : Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 750 Ti / nvd3dum.dll[10.18.13.5382]
	Language : english
	Memory :     8130MB 428KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Right, forgot to update main version.
