### ISSUE TITLE
Long ammo values don't fit the UI

### ISSUE THREAD

**Issue by UserNaem** [LBLuffy/HoloHud#79]
STR:
Equip any weapon with total ammo of greater than 99, and take 14x trip mines 6x shaped charges
Start the heist
Expected behavior:
all digits fit in their places
Actual behavior:
![image](https://user-images.githubusercontent.com/21028464/44757793-54985880-ab4a-11e8-9285-7a191f57bd3e.png)

**Comment by Luffyyy** [comment]
Fixed in latest version
