### ISSUE TITLE
Hacker perk deck crash

### ISSUE THREAD

**Issue by Prooty** [LBLuffy/HoloHud#80]
Crashing when someone use hacker deck active skill
[crashlog.txt](https://github.com/Luffyyy/HoloUI/files/2376587/crashlog.txt)
#

**Comment by Luffyyy** [comment]
No information given to back it up.

**Comment by UserNaem** [comment]
I had the same issue a few days ago, but can't reproduce it anymore, apparently it was fixed in a recent game update.
