### ISSUE TITLE
Trip Mines Don't Fit On UI

### ISSUE THREAD

**Issue by chefman1000000** [LBLuffy/HoloHud#81]
The UI will display fully upgraded tripmines as 4, 3, 2, 1, 0, and then 9 and so on.

**Comment by chefman1000000** [comment]
![1](https://user-images.githubusercontent.com/43297374/45587464-dc64bd80-b8d3-11e8-8a75-8c4378480d19.png)
![image](https://user-images.githubusercontent.com/43297374/45587465-e5558f00-b8d3-11e8-9086-d6c0c4a1e1a1.png)
![image](https://user-images.githubusercontent.com/43297374/45587470-fa322280-b8d3-11e8-9463-17101f130d80.png)

**Comment by Luffyyy** [comment]
Hopefully fixed in latest commit
