### ISSUE TITLE
game crash on startup with language set to german

### ISSUE THREAD

**Issue by Whurrhurr** [LBLuffy/HoloHud#83]
trying to start the game in german nets you this C++ exeception
Application has crashed: C++ exception
mods/base/req/utils/json-0.9.lua:372: Unexpected character at Line 99 character 1: 
 (10) when reading double quoted string
Context: 
: "Angepasste HUD-Rahmenfarbe,
	"Holo/TeammateHost" : "Gastge
                              ^

SCRIPT STACK

next_token() @mods/base/req/utils/json-0.9.lua:372
read_object_value() @mods/base/req/utils/json-0.9.lua:387
read_object_value() @mods/base/req/utils/json-0.9.lua:513
decode() @mods/base/req/utils/json-0.9.lua:519
decode() @mods/base/req/utils/json.lua:14
load_localization_file() @mods/base/lua/LocalizationManager.lua:68
LoadLocalization() @mods/BeardLib/Modules/LocalizationModule.lua:30
func() @mods/BeardLib/Modules/LocalizationModule.lua:23
Call() @mods/base/req/core/Hooks.lua:109
init() @mods/base/lua/LocalizationManager.lua:8
new() core/lib/utils/coreclass.lua:35
core/lib/setups/coresetup.lua:343

**Comment by Luffyyy** [comment]
Fixed a while ago probably
