### ISSUE TITLE
Holoui is outright not working

### ISSUE THREAD

**Issue by MsFizzy** [LBLuffy/HoloHud#87]
so i just got back into payday2 after a few months and had to reinstall my mods, since bl2 hud got shut down i went to thing and so far my efforts to fix it have been unsuccessful. the problem is that the hud just doesnt work, ive tried reinstalling everything and blt registers holoui in the mods tab but there is no customization menu or anything for that fact, its just the normal payday menu.

**Comment by Luffyyy** [comment]
Could you try running the latest version from github?

**Comment by MsFizzy** [comment]
i tried and it still isnt working, blt can see it in the mod updater but not anywhere else.

**Comment by Luffyyy** [comment]
Perhaps you're missing BeardLib?

**Comment by Luffyyy** [comment]
Now you update the mod through BeardLib so it has to show up there (in the updates menu of BeardLib) to confirm that it works. https://modworkshop.net/mydownloads.php?action=view_down&did=14924

**Comment by MsFizzy** [comment]
i do have beardlib but i'll try reinstalling it

**Comment by MsFizzy** [comment]
reinstalling beardlib fixed it, thank you
