### ISSUE TITLE
A Request NOT an ISSUE

### ISSUE THREAD

**Issue by L-Ratio** [LBLuffy/HoloHud#95]
Can we get a feature that allows us to assign multiple colors to backgrounds. Can we also get a feature that allows us to see ecm timer duration, time left of drill kinda like pocohud3/pocohudadditionaltrackers where the timer hovers over the drill, how much is left in our sprint etc

Or are there already UI addons that work for this UI that has trackers?

**Comment by Luffyyy** [comment]
Trackers are not gonna be added this is purely a redesign of the HUD. Mulitple colors could work but I'm currently unsure how to nor have the time to implelement something like that
