### ISSUE TITLE
Text Clipping

### ISSUE THREAD

**Issue by L-Ratio** [LBLuffy/HoloHud#96]
![image](https://user-images.githubusercontent.com/54047268/80702296-14ffdd80-8a9e-11ea-8c3d-a358de303253.png)
Text is clipping where accept and decline is

**Comment by Luffyyy** [comment]
Is that in the privacy thing?

**Comment by L-Ratio** [comment]
> Is that in the privacy thing?

no it's where you join a heist it also happens when you make a contract too I believe

**Comment by Luffyyy** [comment]
Currently only semi fixed. I'm not sure about the top part and I can't test that specific part of the menu atm.
