### ISSUE TITLE
Objective Text Cut Short

### ISSUE THREAD

**Issue by Krimzin** [LBLuffy/HoloHud#98]
Requested by Hinaomi.
![20200704085717_1](https://user-images.githubusercontent.com/9521585/86506942-3c6d8080-be28-11ea-9c99-627984cdd2ab.jpg)
The text in the objective panel, as seen in the top-left corner of the image, appears to be cut short.
Level: Border Crossing

**Comment by Luffyyy** [comment]
I hate GitHub AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
